update_energy:
  name: "Opdater Simple Elforbrug"
  description: "Henter data manuelt fra Eloverblik API"

set_unit:
  name: "Skift enhed"
  description: "Skifter mellem kWh og MWh for visning af forbrug"
  fields:
    unit:
      name: "Enhed"
      description: "Den enhed du vil vise data i"
      required: true
      selector:
        select:
          options:
            - kWh
            - MWh